### ISSUE TITLE
Kernel Patch Issue

### ISSUE THREAD

**Issue by FlyBoyA** [shkwon98/RPi4_Xeno3#1]
Hello guys,
I want to have xenomai RTOS on my raspberry pi 3B
The xenomai ipipe-arm patch with rpi-linux as I see the linux version is 6.1.y and ipipe-arm patch does not have latest patch.
I'm trying to patch the same version 4.19 with 4.19 then too its getting unable to patch the kernel
Do you have idea about?

**Comment by shkwon98** [comment]
@FlyBoyA 
Currently, there are no plans to update this repository.

Though, as far as I know, Xenomai 4 allows deploying directly to the target kernel without using a separate patch model. Additionally, there is a case where Xenomai 4 was successfully built and run on Raspberry 4. (https://www.mail-archive.com/xenomai@xenomai.org/msg21077.html)
I recommend checking the official documentation of Xenomai 4 here(https://evlproject.org/core/build-steps/). You can find out some comments about Raspberry Pi.

I don't know if the above method is equally applicable to the raspberry 3B board, but I think it will be possible. Good luck!

**Comment by FlyBoyA** [comment]
I'm having some challenges following the steps, is the Xenomai 4 build same as Xenomai 3?

**Comment by shkwon98** [comment]
@FlyBoyA 
I can't help you with anything because I don't have any information about the problem you're struggling. Moreover, my comment above was answered to the extent of what I understood based on the official documentation, and I have never built or installed xenomai 4 myself, so it is difficult to give you any more help. Please refer to the official documentation, try it yourself, and contribute if you learn anything new!
